# Generated by Django 3.1.2 on 2020-10-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201006_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attack', models.IntegerField(verbose_name='attack power')),
                ('armor', models.IntegerField(verbose_name='armor bonus')),
                ('heal', models.IntegerField(verbose_name='heal bonus')),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
